theme: jekyll-theme-midnight
collections:
  stu: 
{% for member in .stu %}
  <h2> ![photo]({{ member.image }}) - {{ member.name }}（{{ staff_member.position }}）</h2>
    <p> {{ staff_member.content | markdownify }}</p>
{% endfor %}

