title: Title~~~
author: YF-0111
email: 1155124411@link.cuhk.edu.hk
description: > # this means to ignore newlines until "baseurl:"
  What an awesome page, lalalala
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
 
theme: minima
